import React from "react";

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-2xl font-semibold mb-3">{title}</h2>
    <div className="space-y-3 text-gray-700 leading-relaxed text-sm md:text-base">
      {children}
    </div>
  </div>
);

const Bullet = ({ items }) => (
  <ul className="list-disc pl-5 space-y-2">
    {items.map((item, i) => (
      <li key={i}>{item}</li>
    ))}
  </ul>
);

export const TermsConditions = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>

      <p className="mb-4 text-gray-700">
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.
        This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p className="mb-4 text-gray-700">
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://sudhosanskillsolutions.in/" className="underline text-blue-700">https://sudhosanskillsolutions.in/</a> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
      </p>

      <p className="mb-4 text-gray-700">
        The Platform is owned by Sudhosan Skill Solutions Private Limited, a company incorporated under the Companies Act, 2013 with its registered office at Madhopur Anant, Khairwa Darp, Sheohar, Bihar, 843329 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
      </p>

      <p className="mb-4 text-gray-700">
        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
      </p>

      <p className="mb-4 text-gray-700">
        These Terms of Use relate to your use of our website, educational courses, skill development programmes, career counselling, admission guidance, recruitment services, digital learning content, and any other services offered through the Platform (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>

      <p className="mb-4 text-gray-700">
        For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/learner on the Platform.
      </p>

      <p className="mb-6 text-gray-700 font-semibold">
        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
      </p>

      <Section title="The use of Platform and/or availing of our Services is subject to the following Terms of Use:">
        <Bullet
          items={[
            "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
            "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
            "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
            "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents include and are not limited to course material, design, layout, look and graphics.",
            "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
            "You agree to pay us the charges associated with availing the Services as displayed on the Platform at the time of enrolment or purchase.",
            "You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.",
            "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.",
            "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services."
          ]}
        />
      </Section>

      <Section title="Educational Services — Specific Terms">
        <Bullet
          items={[
            "Enrolment into any course or programme on the Platform is subject to eligibility criteria as specified for each programme. The Platform Owner reserves the right to refuse or cancel enrolment at its sole discretion.",
            "Course content, schedule, fees, duration, and mode of delivery (online/offline) are subject to change. Users will be notified of any material changes in advance where reasonably possible.",
            "Certificates issued by Sudhosan Skill Solutions Private Limited are proprietary and are issued upon successful completion of the programme as per the criteria defined for each course. The Platform Owner does not guarantee employment or admission as an outcome of any programme.",
            "Career counselling, admission guidance, and placement support are advisory services. The Platform Owner does not guarantee any specific outcome including admission to any institution or placement in any organisation.",
            "Users are expected to attend sessions, complete assessments, and follow the code of conduct as communicated by the Platform Owner. Failure to do so may result in suspension or cancellation of enrolment without refund.",
            "Recruitment and staffing services are facilitated by the Platform Owner as an intermediary between candidates and employers. The Platform Owner is not liable for the conduct, terms, or decisions of employers or institutions.",
          ]}
        />
      </Section>

      <Section title="Payments">
        <Bullet
          items={[
            "All payments for courses and services must be made through the payment methods available on the Platform including net banking, credit card, debit card, UPI, and other approved payment instruments.",
            "All fees displayed on the Platform are inclusive of applicable taxes unless stated otherwise. The Platform Owner reserves the right to revise fees at any time.",
            "In the event of a payment failure, you are advised to check with your bank or payment provider before attempting another transaction to avoid double deduction.",
            "The Platform Owner shall not be held responsible for any loss incurred due to transactions made using compromised payment credentials. Users are advised to keep their login credentials and payment information secure."
          ]}
        />
      </Section>

      <Section title="Indemnification">
        <p>
          You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party. Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
        </p>
      </Section>

      <Section title="Governing Law and Jurisdiction">
        <p>
          These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
        </p>
        <p>
          All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Sheohar, Bihar, India.
        </p>
        <p>
          All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
        </p>
      </Section>
    </div>
  );
};

export const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <Section title="Introduction">
        <p>
          This Privacy Policy describes how Sudhosan Skill Solutions Private Limited and its affiliates (collectively "Sudhosan Skill Solutions Private Limited, we, our, us") collect, use, share, protect or otherwise process your information/personal data through our website <a href="https://sudhosanskillsolutions.in/" className="text-blue-700 underline">https://sudhosanskillsolutions.in/</a> (hereinafter referred to as Platform). Please note that you may be able to browse certain sections of the Platform without registering with us. We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.
        </p>
      </Section>

      <Section title="Collection">
        <p>
          We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship. Some of the information that we may collect includes but is not limited to personal data/information provided to us during sign-up/registering or using our Platform such as name, date of birth, address, telephone/mobile number, email ID and/or any such information shared as proof of identity or address. Educational and professional details including qualification, field of study, work experience, and career preferences provided for the purpose of course enrolment, career counselling, or placement support. Some of the sensitive personal data may be collected with your consent, such as your bank account or credit or debit card or other payment instrument information or biometric information such as your facial features or physiological information (in order to enable use of certain features when opted for, available on the Platform), all of the above being in accordance with applicable law(s).
        </p>
        <p className="mt-4">
          You always have the option to not provide information, by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences, and other information that you choose to provide on our Platform. This information is compiled and analysed on an aggregated basis. We will also collect your information related to your transactions on Platform. If you receive an email, a call from a person/association claiming to be Sudhosan Skill Solutions Private Limited seeking any personal data like debit/credit card PIN, net-banking or mobile banking password, we request you to never provide such information. If you have already revealed such information, report it immediately to an appropriate law enforcement agency.
        </p>
      </Section>

      <Section title="Usage">
        <p>
          We use personal data to provide the services you request. To the extent we use your personal data to market to you, we will provide you the ability to opt-out of such uses. We use your personal data to process enrolments, course registrations and payments; to assist in handling and fulfilling services; enhancing customer experience; to resolve disputes; troubleshoot problems; inform you about online and offline offers, courses, programmes, services, and updates; customise your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; conduct marketing research, analysis and surveys; and as otherwise described to you at the time of collection of information. You understand that your access to these products/services may be affected in the event permission is not provided to us.
        </p>
      </Section>

      <Section title="Sharing">
        <p>
          We may share your personal data internally within our group entities, our other corporate entities, and affiliates to provide you access to the services and products offered by them. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out.
        </p>
        <p className="mt-4">
          We may disclose personal data to third parties such as educational institutions, employers, recruitment partners, third party service providers including technology partners, payment processors and other payment methods opted by you. These disclosures may be required for us to provide you access to our services and products offered to you, to comply with our legal obligations, to enforce our user agreement, to facilitate our marketing and advertising activities, to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services.
        </p>
        <p className="mt-4">
          We may disclose personal and sensitive personal data to government agencies or other authorised law enforcement agencies if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We will not sell your personal data to third parties for their own independent marketing purposes without your explicit consent.
        </p>
      </Section>

      <Section title="Security Precautions">
        <p>
          To protect your personal data from unauthorised access or disclosure, loss or misuse, we adopt reasonable security practices and procedures. Once your information is in our possession or whenever you access your account information, we adhere to our security guidelines to protect it against unauthorised access and offer the use of a secure server. However, the transmission of information is not completely secure for reasons beyond our control. By using the Platform, the users accept the security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for their account.
        </p>
      </Section>

      <Section title="Data Deletion and Retention">
        <p>
          You have an option to delete your account by visiting your profile and settings on our Platform, this action would result in you losing all information related to your account. You may also write to us at the contact information provided below to assist you with these requests. We may in event of any pending grievance, claims, or any other services we may refuse or delay deletion of the account. Once the account is deleted, you will lose access to the account.
        </p>
        <p className="mt-4">
          We retain your personal data information for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. However, we may retain data related to you if we believe it may be necessary to prevent fraud or future abuse or for other legitimate purposes. We may continue to retain your data in anonymised form for analytical and research purposes.
        </p>
      </Section>

      <Section title="Your Rights">
        <p>
          You may access, rectify, and update your personal data directly through the functionalities provided on the Platform.
        </p>
      </Section>

      <Section title="Consent">
        <p>
          By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any personal data relating to other people, you represent that you have the authority to do so and permit us to use the information in accordance with this Privacy Policy.
        </p>
        <p className="mt-4">
          You, while providing your personal data over the Platform or any partner platforms or establishments, consent to us (including our other corporate entities, affiliates, lending partners, technology partners, marketing channels, business partners and other third parties) to contact you through SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy.
        </p>
        <p className="mt-4">
          You have an option to withdraw your consent that you have already provided by writing to the Grievance Officer at the contact information provided below. Please mention "Withdrawal of consent for processing personal data" in your subject line of your communication. We may verify such requests before acting on our request. However, please note that your withdrawal of consent will not be retrospective and will be in accordance with the Terms of Use, this Privacy Policy, and applicable laws. In the event you withdraw consent given to us under this Privacy Policy, we reserve the right to restrict or deny the provision of our services for which we consider such information to be necessary.
        </p>
      </Section>

      <Section title="Changes to this Privacy Policy">
        <p>
          Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We may alert / notify you about the significant changes to the Privacy Policy, in the manner as may be required under applicable laws.
        </p>
      </Section>

      <Section title="Grievance Officer">
        <ul className="list-disc pl-6 space-y-2 text-gray-700">
          <li>
            <strong>Name of the Office:</strong> Privacy Compliance Office/Director Office
          </li>
          <li>
            <strong>Designation:</strong> Data Protection Officer / Director
          </li>
          <li>
            <strong>Name and Address of the Company:</strong> Sudhosan Skill Solutions Private Limited – Sheohar, Bihar, 843329
          </li>
          <li>
            <strong>Contact us:</strong>{' '}
            <a href="mailto:info@sudhosanskillsolutions.in" className="text-blue-700 underline">
              info@sudhosanskillsolutions.in
            </a>
          </li>
          <li>
            <strong>Time:</strong> Monday – Friday (10:00 – 17:00)
          </li>
        </ul>
      </Section>
    </div>
  );
};

export const RefundPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <h1 className="text-3xl font-bold mb-6">Refund & Cancellation Policy</h1>
      <p className="mb-8 text-gray-700">
        This refund and cancellation policy outlines how you can cancel or seek a refund for a course or service that you have purchased through the Platform. Under this policy:
      </p>
      <ul className="list-disc pl-6 space-y-4 text-gray-700">
        <li>
          <b>Cancellations</b> will only be considered if the request is made within <b>7 days</b> of enrolment or payment, provided the course or service has <b>not yet commenced</b>. Once a course, programme, or any session has commenced — including online sessions, offline classes, orientation, or any first interaction with the course content — cancellation requests will not be entertained.
        </li>
        <li>
          For counselling and advisory services such as career counselling or admission guidance, cancellation is <b>not applicable once the first session or consultation has been conducted</b>.
        </li>
        <li>
          For placement and recruitment services, <b>no cancellation or refund will be applicable once the candidate profile has been submitted</b> to any employer or institution on behalf of the candidate.
        </li>
        <li>
          <b>Cancellation requests</b> must be submitted in writing to <a href="mailto:info@sudhosanskillsolutions.in" className="text-blue-700 underline">info@sudhosanskillsolutions.in</a> with your name, registered mobile number, course name, enrolment date, and reason for cancellation.
        </li>
        <li>
          If a valid cancellation request is raised within 7 days of enrolment and the course or service has not commenced, a <b>full refund will be processed after deducting any applicable payment gateway transaction charges</b>.
        </li>
        <li>
          In case of receipt of damaged or defective study material or digital content, please report to our customer service team within <b>7 days of receipt</b>. The request will be reviewed and an appropriate resolution will be provided.
        </li>
        <li>
          If you feel that the service received is <b>not as described on the Platform</b> or as per your expectations, you must bring it to the notice of our customer service within <b>7 days of commencement</b> of the service. The customer service team after looking into your complaint will take an appropriate decision.
        </li>
        <li>
          In the event a course is cancelled or discontinued by <b>Sudhosan Skill Solutions Private Limited</b>, a full refund of the course fee will be provided to all enrolled users.
        </li>
        <li>
          <b>Registration fees, application fees, or processing fees</b>, if charged separately, are <b>non-refundable under any circumstances</b>.
        </li>
        <li>
          <b>Pay-After-Placement programme fees</b> that are deducted after a successful placement are <b>non-refundable once employment has commenced</b>.
        </li>
        <li>
          In case of any refunds approved by Sudhosan Skill Solutions Private Limited, <b>it will take 15 days for the refund to be processed</b> to you.
        </li>
      </ul>
    </div>
  );
};

export default function LegalPages() {
  return (
    <div className="space-y-16">
      <TermsConditions />
      <PrivacyPolicy />
      <RefundPolicy />
    </div>
  );
}
